### ISSUE TITLE
Cannot find module ws, however ws is installed

### ISSUE THREAD

**Issue by AddictArts** [hschneider/neutralino-ext-node#1]
Here is the error:

WS is installed to the that extensions/node ... node_modules folder.

```
C:\box\neu\neutralino-ext-node
❯ .\extensions\node\run.cmd .
Debugger listening on ws://127.0.0.1:9229/66645dff-2aea-4ae4-9ff6-477ab25fa42e
For help, see: https://nodejs.org/en/docs/inspector
---
NodeJS Version: v21.7.2
NodeJS Path: C:\box\neu\neutralino-ext-node\extensions\node\_runtime\nodejs-win\Scripts\node.exe
---
node:internal/modules/cjs/loader:1145
  throw err;
  ^

Error: Cannot find module 'ws'
Require stack:
- C:\box\neu\neutralino-ext-node\extensions\node\neutralino-extension.js
- C:\box\neu\neutralino-ext-node\extensions\node\main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at NeutralinoExtension.run (C:\box\neu\neutralino-ext-node\extensions\node\neutralino-extension.js:71:27)
    at Object.<anonymous> (C:\box\neu\neutralino-ext-node\extensions\node\main.js:53:5)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\box\\neu\\neutralino-ext-node\\extensions\\node\\neutralino-extension.js',
    'C:\\box\\neu\\neutralino-ext-node\\extensions\\node\\main.js'
  ]
}

Node.js v21.7.2
```

Thanks for the help.

**Comment by hschneider** [comment]
Sorry, this was not clear as it should be in the manual.  Have fixed it now.

If you use embedded Node, you'll have to install the ws module as follows:
```
cd extensions\node
install.cmd
npm.cmd install ws
```

If you use a global Node-installation, then this is the way:
```
npm install ws --save
```

**Comment by AddictArts** [comment]
Thanks. Now I can run it using the run.cmd from a powershell prompt. However, the `neu run` cannot start it. Too bad we don't get anything in the log, or better feedback on whatever the error is. The rust example is now working and the curl one does as well. Thanks

**Comment by AddictArts** [comment]
Here is an example of running from the pwsh

```
C:\box\neu\neutralino-ext-node
❯ .\extensions\node\run.cmd .
Debugger listening on ws://127.0.0.1:9229/865fee1f-6e79-4035-a7b0-f4154f90a178
For help, see: https://nodejs.org/en/docs/inspector
---
NodeJS Version: v21.7.2
NodeJS Path: C:\box\neu\neutralino-ext-node\extensions\node\_runtime\nodejs-win\Scripts\node.exe
---
WebSocket Error: Error: connect ECONNREFUSED 127.0.0.1:80
WebSocket closed: 1006 -
```

For whatever reason neutralino is not starting node. I added the double backslash and that didn't resolve it like it did the rust. The socket error above is expected since neutralino is not running.

**Comment by AddictArts** [comment]
If this helps I see what is happening, captured stdout from the node process.

```
WebSocket closed: 1006 - 
```

**Comment by AddictArts** [comment]
So, it turns out for Windows at least these lines are what gets executed instead of reading from stdin the token etc,

````
        if(process.argv.length > 2) {
            this.port = process.argv[2].split('=')[1];
            this.token = process.argv[3].split('=')[1];
            this.connectToken = '';
            this.idExtension = process.argv[4].split('=')[1];
            this.urlSocket = `ws://127.0.0.1:${this.port}?extensionId=${this.idExtension}`;
        }
````

**Comment by AddictArts** [comment]
While now working, the node process spun up becomes a zombie process. Maybe this is only dev mode and not a build. Thanks for the help.

**Comment by hschneider** [comment]
```
WebSocket Error: Error: connect ECONNREFUSED 127.0.0.1:80
```
Port 80 should not be used for websockets. Set it to some port higher than 1024 or to 0, so it gets a random port.

If you start the extension manually with run.cmd, then it runs detached from the Neutralino main process. That's what you recognize as a zombie process.

**Comment by AddictArts** [comment]
> ```
> WebSocket Error: Error: connect ECONNREFUSED 127.0.0.1:80
> ```
> 
> Port 80 should not be used for websockets. Set it to some port higher than 1024 or to 0, so it gets a random port.
> 
> If you start the extension manually with run.cmd, then it runs detached from the Neutralino main process. That's what you recognize as a zombie process.

Thanks, the process was started by neutralino. I think the argument count is different in Windows than Linux and it was trying to use the path you are pointing out, starting the extension manually. I do have it working now as intended. I will try and see what the argument count is under windows, my guess is greater than 2 for argv, thus it went into the if body.

**Comment by hschneider** [comment]
The args > %1 in run.cmd play no role in Neutralino 5. Meanwhile I was able to verify the behavior on a Windows machine. There seems to be something other broken under Windows. I see the Node process running, but the websocket connection seems to be dead. 

I will dig further and keep you posted.

**Comment by hschneider** [comment]
Fixed it. 

The problem was the -g flag in npm.cmd. It behaves different on macOS/Linux and Windows.

Replace all .cmd files in the extensions/node folder. 
Then run
```
.\npm.cmd install ws
```
again.

BTW:
You might also have a look at the Bun Extension. It's nearly 100% NodeJS compatible and runs on Windows as well:
https://github.com/hschneider/neutralino-ext-bun

**Comment by AddictArts** [comment]
> The args > %1 in run.cmd play no role in Neutralino 5.

I am getting a different count on Windows running the code as it was when I first made this issue.

`process argv length 5`

I had the node process log this in the constructor for the web socket. I am using v5, so there must be another explanation. Thanks again.


PS: I thought Bun on Windows was a joke, it was an April 1st release.

**Comment by hschneider** [comment]
Please replace all .cmd files and make sure that you use Neutralino 5.x.
Bun for Windows works since its last Beta, no April joke :-)

**Comment by AddictArts** [comment]
@hschneider The issue is this in the `run.cmd` is `%2=%3 %4=%5 %6=%7` which turn into `= = =` when run as an extension.

Thus making the extra arguments, maybe you changed run.cmd, I didn't look. The next issue I have is node stays running on Windows even though in the socket close I added process.exit(). That is not your issue, just an observation.

**Comment by hschneider** [comment]
This has been removed. There are also changes in other files. 
That's why you should replace all cmd files and reinstall the ws module.

**Comment by hschneider** [comment]
The Node process exists fine. I think this issue will solve itself, when you updated to the latest repo version.
I tested it on Win11 Pro with embedded NodeJS v21.5.0:

https://app.screencast.com/YKSr8F3KlNgCS

**Comment by AddictArts** [comment]
Thanks @hschneider 

Pulled the latest and it does run out of the box following README, thank you, very appreciated.

FYI: Procs below is a rust replacement for ps

The node.exe process does linger and is orphaned. See the proc output below. You can see neutralino-win_x64.exe spawns the process 33620, then I kill / exit / close, the neutralino-win_x64.exe process and the node process remains running. And I know it is the child by pid and args `.\extensions\node\_runtime\nodejs-win\Scripts\node.exe  --inspect .\extensions\node\main.js`.

````
❯ procs -t -i ppid node
             PID   User   │ CPU MEM CPU Time Parent PID │ Command
                          │ [%] [%]                     │
 └┬───────── 16312 E26368 │ 0.0 0.1 00:02:06       6912 │ sihost.exe
  └┬──────── 26096 E26368 │ 0.0 0.2 00:04:19      16312 │ WindowsTerminal.exe
   └┬─────── 72960 E26368 │ 0.0 0.2 00:00:15      26096 │ pwsh.exe
    └┬────── 69136 E26368 │ 0.0 0.1 00:00:00      72960 │ node.exe
     └┬───── 58072 E26368 │ 0.0 0.0 00:00:00      69136 │ neutralino-win_x64.exe
      ├┬──── 11908 E26368 │ 0.0 0.2 00:00:00      58072 │ msedgewebview2.exe
      │├──── 43892 E26368 │ 0.0 0.0 00:00:00      11908 │ msedgewebview2.exe
      │├──── 71760 E26368 │ 0.0 0.1 00:00:00      11908 │ msedgewebview2.exe
      │├──── 76568 E26368 │ 0.0 0.2 00:00:00      11908 │ msedgewebview2.exe
      │├──── 78764 E26368 │ 0.0 0.0 00:00:00      11908 │ msedgewebview2.exe
      │├──── 80080 E26368 │ 0.0 0.0 00:00:00      11908 │ msedgewebview2.exe
      │├──── 81032 E26368 │ 0.0 0.2 00:00:00      11908 │ msedgewebview2.exe
      │└──── 84316 E26368 │ 0.0 0.0 00:00:00      11908 │ msedgewebview2.exe
      └┬──── 33620 E26368 │ 0.0 0.0 00:00:00      58072 │ cmd.exe
       ├──── 24616 E26368 │ 0.0 0.1 00:00:00      33620 │ node.exe
       └──── 38032 E26368 │ 0.0 0.0 00:00:00      33620 │ conhost.exe

# Close the app, kill it, node proc still remains

❯ procs -t -i ppid node
        PID   User   │ CPU MEM CPU Time Parent PID │ Command
                     │ [%] [%]                     │
 └┬──── 33620 E26368 │ 0.0 0.0 00:00:00      58072 │ cmd.exe
  └──── 24616 E26368 │ 0.0 0.1 00:00:00      33620 │ node.exe
````

**Comment by hschneider** [comment]
Thanks for testing.
I cannot confirm the orphan process on my system. However, I added a kill-switch to make sure the extension quits.
You can test by either pulling the latest version or by replacing this file:
extensions/node/neutralino-extension.js

**Comment by AddictArts** [comment]
@hschneider 

As I suspected and had tried that same thing myself, it does not resolve the issue. I have duplicated this issue on 2 different Windows 11 computers. One is Windows 11 Home and the other Windows 11 Pro latest Windows updates and using powershell. However, I tried CMD and the same issue persists.

```
❯ procs -t -i ppid node
             PID   User   │ CPU MEM CPU Time Parent PID │ Command
                          │ [%] [%]                     │
 └┬───────── 16312 E26368 │ 0.0 0.1 00:02:07       6912 │ sihost.exe
  └┬──────── 26096 E26368 │ 0.0 0.2 00:04:20      16312 │ WindowsTerminal.exe
   └┬─────── 72960 E26368 │ 0.0 0.2 00:00:16      26096 │ pwsh.exe
    └┬────── 71500 E26368 │ 0.0 0.1 00:00:00      72960 │ node.exe
     └┬───── 19892 E26368 │ 0.0 0.0 00:00:00      71500 │ neutralino-win_x64.exe
      ├┬──── 74524 E26368 │ 0.0 0.2 00:00:00      19892 │ msedgewebview2.exe
      │├──── 18396 E26368 │ 0.0 0.0 00:00:00      74524 │ msedgewebview2.exe
      │├──── 19000 E26368 │ 0.0 0.1 00:00:00      74524 │ msedgewebview2.exe
      │├──── 25912 E26368 │ 0.0 0.0 00:00:00      74524 │ msedgewebview2.exe
      │├──── 51144 E26368 │ 0.0 0.0 00:00:00      74524 │ msedgewebview2.exe
      │├──── 64176 E26368 │ 0.0 0.2 00:00:00      74524 │ msedgewebview2.exe
      │├──── 70840 E26368 │ 0.0 0.1 00:00:00      74524 │ msedgewebview2.exe
      │└──── 75272 E26368 │ 0.0 0.0 00:00:00      74524 │ msedgewebview2.exe
      └┬──── 83768 E26368 │ 0.0 0.0 00:00:00      19892 │ cmd.exe
       ├──── 2020  E26368 │ 0.0 0.0 00:00:00      83768 │ conhost.exe
       └──── 15944 E26368 │ 0.0 0.1 00:00:00      83768 │ node.exe

❯ procs -t -i ppid node
        PID   User   │ CPU MEM CPU Time Parent PID │ Command
                     │ [%] [%]                     │
 └┬──── 83768 E26368 │ 0.0 0.0 00:00:00      19892 │ cmd.exe
  └──── 15944 E26368 │ 0.0 0.1 00:00:00      83768 │ node.exe
```

**Comment by AddictArts** [comment]
![image](https://github.com/hschneider/neutralino-ext-node/assets/911906/9eacce07-bf15-4d06-8ef7-2d3c3bc6dd97)

This is what happens after closing the app.

**Comment by hschneider** [comment]
Rather strange. As you can see in the video I posted before, mine behaves different.

What happens on your system, if you change this line

`process.kill(pid, 'SIGHUP');`

to 

`process.kill(pid, 'SIGTERM');`

**Comment by AddictArts** [comment]
@hschneider Thanks and I really appreciate the help here. I mean the below with respect.

The problem with your screencast is you neglect to scroll down in Task manager to background processes. And there you will find that node process. It may appear to be killed, but it drops into a background state and is not listed with all the other processes. Use Process Explorer or command line procs, much better way to observe this kind of thing.

This is why I added the screenshot.

**Comment by hschneider** [comment]
procs makes no difference:

https://app.screencast.com/7ZWDeg2lowHGx

and

https://app.screencast.com/aI9Olri3Q5USI

Did you try the SIGTERM thing ?

**Comment by hschneider** [comment]
What have your 2 machines in common?
Maybe some antivir software?

Which Node version do you use?

**Comment by AddictArts** [comment]
> What have your 2 machines in common? Maybe some antivir software?
> 
> Which Node version do you use?

Nothing in common other than Windows OS. One is work and totally different security controls etc. The other is a Microsoft Surface Pro 9 that is a personal machine, Windows defender.

SIGTERM did nothing


```
...\neutralino-ext-node\extensions\node\_runtime\nodejs-win\Scripts
❯ .\node.exe --version
v21.7.2
```

**Comment by AddictArts** [comment]
Thanks for trying, I see the procs showing no node.exe running in your screencast. Could it be firewall? are you running a firewall?

Seems like Windows has some different behavior 

https://github.com/dart-lang/sdk/issues/49234

https://stackoverflow.com/questions/3235218/how-terminate-child-processes-when-parent-process-terminated-in-c-sharp

**Comment by hschneider** [comment]
My Node version is the same and the Windows integrated FW is active.
It really looks similar to the Windows issues you posted.
You can try SIGKILL instead of SIGTERM.

**Comment by hschneider** [comment]
You can also give this one a try:
https://www.npmjs.com/package/tree-kill

**Comment by hschneider** [comment]
One more thing, you should try first:
Remove the `--inspect` from this line in `run.cmd`:
```
%NODE_VIRTUAL_ENV%\Scripts\node.exe --inspect %1\extensions\node\main.js
```

**Comment by hschneider** [comment]
Not a nice but maybe working solution:
```
exec('taskkill /F /pid '+pid);
```

**Comment by AddictArts** [comment]
Found the issue https://github.com/hschneider/neutralino-ext-node/blob/c5c608b4d5e75c1f4e398d9eb1d7f90d68b1bce2/extensions/node/neutralino-extension.js#L90

`d` is not defined in that callback for socket.on('message' ...

Changed to `if(msg.event === 'windowClose' || msg.event === 'appClose')`. It was throwing an exception there so no matter what I did it didn't matter. Now it dies properly.

Here is my complete diff / patch

```
❯ git diff
diff --git a/extensions/node/neutralino-extension.js b/extensions/node/neutralino-extension.js
index 25c7a35..3f2e1cb 100644
--- a/extensions/node/neutralino-extension.js
+++ b/extensions/node/neutralino-extension.js
@@ -87,11 +87,9 @@ class NeutralinoExtension {

             try {
                 if(self.termOnWindowClose) {
-                    if(d.event === 'windowClose' || d.event === 'appClose') {
+                    if(msg.event === 'windowClose' || msg.event === 'appClose') {
                         try {
-                            let pid = process.pid;
-                            process.kill(pid, 'SIGHUP');
-                            return;
+                            process.exit(0);
                         }
                         catch (e) {}
                         return;
```

I have no idea how you had it working with that underfined `d`.

**Comment by hschneider** [comment]
Wow! Thanks for debugging!
Think the undefined d terminated the process anyway, so this error was never detected.
Nice job. Time to close this issue :-)
